# read

In [1]:
import pandas as pd; pd.set_option('display.max_columns', None)
import numpy as np; np.random.seed(0)
import matplotlib.pyplot as plt
import seaborn as sns

train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon_logistics/data/train_df.csv', encoding='cp949')
test  = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon_logistics/data/test_df.csv', encoding='cp949')
sub   = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon_logistics/data/sample_submission.csv', encoding='cp949')

In [2]:
train.head()

index     SEND_SPG_INNB      REC_SPG_INNB DL_GD_LCLS_NM DL_GD_MCLS_NM  \
0      0  1129000014045300  5011000220046300          패션의류            상의   
1      1  1135000009051200  5011000178037300         생활/건강          반려동물   
2      2  1135000030093100  5011000265091400          패션의류        기타패션의류   
3      3  1154500002014200  5011000315087400            식품           농산물   
4      4  1165000021008300  5011000177051200            식품          가공식품   

   INVC_CONT  
0          3  
1          3  
2          9  
3         10  
4          3

# 슬라이싱

In [3]:
# send
for df in [train, test]:
    df['send_1_5'] = df['SEND_SPG_INNB'].astype('str').str[:5]  # 1 ~ 5
    df['send_6_9'] = df['SEND_SPG_INNB'].astype('str').str[5:9] # 6 ~ 9
    df['send_10']  = df['SEND_SPG_INNB'].astype('str').str[9]   # 10
    df['send_11_16'] = df['SEND_SPG_INNB'].astype('str').str[10:]

In [4]:
train.head()

index     SEND_SPG_INNB      REC_SPG_INNB DL_GD_LCLS_NM DL_GD_MCLS_NM  \
0      0  1129000014045300  5011000220046300          패션의류            상의   
1      1  1135000009051200  5011000178037300         생활/건강          반려동물   
2      2  1135000030093100  5011000265091400          패션의류        기타패션의류   
3      3  1154500002014200  5011000315087400            식품           농산물   
4      4  1165000021008300  5011000177051200            식품          가공식품   

   INVC_CONT send_1_5 send_6_9 send_10 send_11_16  
0          3    11290     0001       4     045300  
1          3    11350     0000       9     051200  
2          9    11350     0003       0     093100  
3         10    11545     0000       2     014200  
4          3    11650     0002       1     008300

In [5]:
# rec
for df in [train, test]:
    for i in range(16):
        df[f'rec_{i + 1}'] = df['REC_SPG_INNB'].astype('str').str[i]

In [6]:
train.head()

index     SEND_SPG_INNB      REC_SPG_INNB DL_GD_LCLS_NM DL_GD_MCLS_NM  \
0      0  1129000014045300  5011000220046300          패션의류            상의   
1      1  1135000009051200  5011000178037300         생활/건강          반려동물   
2      2  1135000030093100  5011000265091400          패션의류        기타패션의류   
3      3  1154500002014200  5011000315087400            식품           농산물   
4      4  1165000021008300  5011000177051200            식품          가공식품   

   INVC_CONT send_1_5 send_6_9 send_10 send_11_16 rec_1 rec_2 rec_3 rec_4  \
0          3    11290     0001       4     045300     5     0     1     1   
1          3    11350     0000       9     051200     5     0     1     1   
2          9    11350     0003       0     093100     5     0     1     1   
3         10    11545     0000       2     014200     5     0     1     1   
4          3    11650     0002       1     008300     5     0     1     1   

  rec_5 rec_6 rec_7 rec_8 rec_9 rec_10 rec_11 rec_12 rec_13 rec_14 rec_15  \
0     0     0     0     2     2      0      0      4      6      3      0   
1     0     0     0     1     7      8      0      3      7      3      0   
2     0     0     0     2     6      5      0      9      1      4      0   
3     0     0     0     3     1      5      0      8      7      4      0   
4     0     0     0     1     7      7      0      5      1      2      0   

  rec_16  
0      0  
1      0  
2      0  
3      0  
4      0

# drop

In [7]:
drop_cols = ['index', 'SEND_SPG_INNB', 'REC_SPG_INNB']
train.drop(drop_cols, axis=1, inplace=True)
test.drop(drop_cols, axis=1, inplace=True)

In [8]:
train.head()

DL_GD_LCLS_NM DL_GD_MCLS_NM  INVC_CONT send_1_5 send_6_9 send_10 send_11_16  \
0          패션의류            상의          3    11290     0001       4     045300   
1         생활/건강          반려동물          3    11350     0000       9     051200   
2          패션의류        기타패션의류          9    11350     0003       0     093100   
3            식품           농산물         10    11545     0000       2     014200   
4            식품          가공식품          3    11650     0002       1     008300   

  rec_1 rec_2 rec_3 rec_4 rec_5 rec_6 rec_7 rec_8 rec_9 rec_10 rec_11 rec_12  \
0     5     0     1     1     0     0     0     2     2      0      0      4   
1     5     0     1     1     0     0     0     1     7      8      0      3   
2     5     0     1     1     0     0     0     2     6      5      0      9   
3     5     0     1     1     0     0     0     3     1      5      0      8   
4     5     0     1     1     0     0     0     1     7      7      0      5   

  rec_13 rec_14 rec_15 rec_16  
0      6      3      0      0  
1      7      3      0      0  
2      1      4      0      0  
3      7      4      0      0  
4      1      2      0      0

In [9]:
train[test.columns] = train[test.columns].astype('category')
test[test.columns]  = test[test.columns].astype('category')

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32000 entries, 0 to 31999
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype   
---  ------         --------------  -----   
 0   DL_GD_LCLS_NM  32000 non-null  category
 1   DL_GD_MCLS_NM  32000 non-null  category
 2   INVC_CONT      32000 non-null  int64   
 3   send_1_5       32000 non-null  category
 4   send_6_9       32000 non-null  category
 5   send_10        32000 non-null  category
 6   send_11_16     32000 non-null  category
 7   rec_1          32000 non-null  category
 8   rec_2          32000 non-null  category
 9   rec_3          32000 non-null  category
 10  rec_4          32000 non-null  category
 11  rec_5          32000 non-null  category
 12  rec_6          32000 non-null  category
 13  rec_7          32000 non-null  category
 14  rec_8          32000 non-null  category
 15  rec_9          32000 non-null  category
 16  rec_10         32000 non-null  category
 17  rec_11         32000 non-null  

# modeling

In [11]:
X = train.drop('INVC_CONT', axis=1)
y = train['INVC_CONT']

In [12]:
!pip install optuna

     |████████████████████████████████| 308 kB 5.2 MB/s 
     |████████████████████████████████| 209 kB 50.9 MB/s 
     |████████████████████████████████| 80 kB 9.1 MB/s 
     |████████████████████████████████| 75 kB 4.6 MB/s 
     |████████████████████████████████| 49 kB 6.3 MB/s 
     |████████████████████████████████| 149 kB 50.0 MB/s 
     |████████████████████████████████| 112 kB 50.1 MB/s 
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11136 sha256=601dac42c94b41ce768e1203f397d54add11cae94a30260837ff8d59fc7c7c8d
  Stored in directory: /root/.cache/pip/wheels/9f/18/84/8f69f8b08169c7bae2dde6bd7daf0c19fca8c8e500ee620a28
Successfully built pyperclip


In [13]:
!pip install catboost

     |████████████████████████████████| 76.3 MB 1.2 MB/s 


In [19]:
import optuna
from sklearn.model_selection import train_test_split
from catboost import CatBoostRegressor
from sklearn.metrics import mean_squared_error

def objective(trial):
    param = {
        "random_state":42,
        'learning_rate' : trial.suggest_loguniform('learning_rate', 0.01, 0.05),
        'bagging_temperature' :trial.suggest_loguniform('bagging_temperature', 0.01, 100.00),
        "n_estimators":trial.suggest_int("n_estimators", 500, 5000),
        "max_depth":trial.suggest_int("max_depth", 4, 16),
        'random_strength' :trial.suggest_int('random_strength', 0, 100),
        "colsample_bylevel":trial.suggest_float("colsample_bylevel", 0.4, 1.0),
        "l2_leaf_reg":trial.suggest_float("l2_leaf_reg",1e-8,3e-5),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
        "max_bin": trial.suggest_int("max_bin", 200, 500),
        'od_type': trial.suggest_categorical('od_type', ['IncToDec', 'Iter']),
    }

    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

    cat_feat = range(test.shape[1])
    
    model = CatBoostRegressor(**param)
    model.fit(
        X_train, y_train, 
        eval_set=[(X_train, y_train), (X_val, y_val)], 
        early_stopping_rounds=35, 
        cat_features=cat_feat, 
        verbose=100
    )

    pred = model.predict(X_val)
    rmse = mean_squared_error(y_val, pred, squared=False)

    return rmse 

In [20]:
from optuna.samplers import TPESampler

sampler = TPESampler(seed=0)
study = optuna.create_study(
    study_name='cat_param_optuna', 
    direction='minimize', 
    sampler=sampler
)

study.optimize(objective, n_trials=10)
print(study.best_value)
print(study.best_trial.params)

[I 2021-12-22 00:47:27,457] A new study created in memory with name: cat_param_optuna


0:	learn: 6.0131346	test: 6.0131400	test1: 4.5614697	best: 4.5614697 (0)	total: 106ms	remaining: 5m 40s
100:	learn: 5.9218919	test: 5.9145789	test1: 4.4875928	best: 4.4875928 (100)	total: 18.4s	remaining: 9m 25s
200:	learn: 5.8474356	test: 5.8561032	test1: 4.4580157	best: 4.4580157 (200)	total: 36.1s	remaining: 9m
300:	learn: 5.7823749	test: 5.7635851	test1: 4.4484549	best: 4.4484549 (300)	total: 49.9s	remaining: 8m 2s
400:	learn: 5.7483687	test: 5.7389831	test1: 4.4406491	best: 4.4406491 (400)	total: 1m 3s	remaining: 7m 23s
500:	learn: 5.5650510	test: 5.4995353	test1: 4.4294373	best: 4.4294312 (499)	total: 1m 22s	remaining: 7m 24s
600:	learn: 5.1245610	test: 5.2870482	test1: 4.4098898	best: 4.4098898 (600)	total: 1m 56s	remaining: 8m 25s
700:	learn: 4.8007070	test: 5.1857033	test1: 4.4002541	best: 4.3998413 (694)	total: 2m 38s	remaining: 9m 29s
800:	learn: 4.6123541	test: 5.1523160	test1: 4.3918880	best: 4.3913173 (792)	total: 3m 19s	remaining: 10m 2s
Stopped by overfitting detector  

[I 2021-12-22 00:51:11,810] Trial 0 finished with value: 4.388303869321673 and parameters: {'learning_rate': 0.02418823488257283, 'bagging_temperature': 7.257005721594282, 'n_estimators': 3213, 'max_depth': 11, 'random_strength': 42, 'colsample_bylevel': 0.7875364678399936, 'l2_leaf_reg': 1.3133240465768148e-05, 'min_child_samples': 90, 'max_bin': 490, 'od_type': 'Iter'}. Best is trial 0 with value: 4.388303869321673.


0:	learn: 5.3954803	test: 5.3951270	test1: 6.9883202	best: 6.9883202 (0)	total: 54.7ms	remaining: 4m 15s
100:	learn: 5.3119115	test: 5.2917382	test1: 6.8988390	best: 6.8988390 (100)	total: 3.28s	remaining: 2m 28s
200:	learn: 5.2853377	test: 5.2459212	test1: 6.8468532	best: 6.8468453 (199)	total: 6.59s	remaining: 2m 26s
300:	learn: 5.2593977	test: 5.2136648	test1: 6.7924004	best: 6.7924004 (300)	total: 9.78s	remaining: 2m 21s
400:	learn: 5.2476356	test: 5.1918874	test1: 6.7505570	best: 6.7505570 (400)	total: 12.9s	remaining: 2m 17s
500:	learn: 5.2217107	test: 5.1557951	test1: 6.6894150	best: 6.6894150 (500)	total: 16.1s	remaining: 2m 14s
600:	learn: 5.1706152	test: 5.0776063	test1: 6.5034130	best: 6.5034030 (599)	total: 20s	remaining: 2m 15s
700:	learn: 5.1334868	test: 5.0252920	test1: 6.3761760	best: 6.3761760 (700)	total: 24.1s	remaining: 2m 16s
800:	learn: 5.1053385	test: 4.9909227	test1: 6.2870357	best: 6.2868550 (798)	total: 28.2s	remaining: 2m 15s
900:	learn: 5.0851869	test: 4.963

[I 2021-12-22 00:52:21,893] Trial 1 finished with value: 6.028265307013375 and parameters: {'learning_rate': 0.023425112449960254, 'bagging_temperature': 1.871450068624068, 'n_estimators': 4666, 'max_depth': 4, 'random_strength': 8, 'colsample_bylevel': 0.41213103846419546, 'l2_leaf_reg': 2.498026916798266e-05, 'min_child_samples': 79, 'max_bin': 461, 'od_type': 'IncToDec'}. Best is trial 0 with value: 4.388303869321673.


0:	learn: 5.7368745	test: 5.7357913	test1: 5.7892371	best: 5.7892371 (0)	total: 744ms	remaining: 12m 46s
100:	learn: 5.5068930	test: 5.4966684	test1: 5.5821662	best: 5.5821662 (100)	total: 25.6s	remaining: 3m 56s
200:	learn: 5.3975194	test: 5.4363371	test1: 5.5293664	best: 5.5293650 (199)	total: 51.9s	remaining: 3m 34s
300:	learn: 5.3167816	test: 5.3737255	test1: 5.4831648	best: 5.4831648 (300)	total: 1m 16s	remaining: 3m 4s
400:	learn: 5.2400185	test: 5.3390312	test1: 5.4540423	best: 5.4540423 (400)	total: 1m 44s	remaining: 2m 44s
500:	learn: 5.1653867	test: 5.3135314	test1: 5.4445745	best: 5.4445650 (497)	total: 2m 13s	remaining: 2m 21s
600:	learn: 4.8842219	test: 5.1799486	test1: 5.3109760	best: 5.3109760 (600)	total: 3m	remaining: 2m 9s
700:	learn: 4.5661980	test: 5.0860392	test1: 5.2428567	best: 5.2428273 (698)	total: 4m 8s	remaining: 1m 57s
Stopped by overfitting detector  (35 iterations wait)

bestTest = 5.234252665
bestIteration = 752

Shrink model to first 753 iterations.


[I 2021-12-22 00:57:30,797] Trial 2 finished with value: 5.234252665095998 and parameters: {'learning_rate': 0.021016492243075374, 'bagging_temperature': 13.246974647468454, 'n_estimators': 1032, 'max_depth': 12, 'random_strength': 14, 'colsample_bylevel': 0.9668013502297503, 'l2_leaf_reg': 1.566023116928465e-05, 'min_child_samples': 44, 'max_bin': 279, 'od_type': 'IncToDec'}. Best is trial 0 with value: 4.388303869321673.


0:	learn: 6.0318752	test: 6.0245079	test1: 4.3917668	best: 4.3917668 (0)	total: 478ms	remaining: 26m 5s
100:	learn: 5.9260951	test: 5.9410561	test1: 4.3222709	best: 4.3222709 (100)	total: 15.4s	remaining: 8m 5s
200:	learn: 5.8718084	test: 5.8907748	test1: 4.2887265	best: 4.2887265 (200)	total: 28.4s	remaining: 7m 15s
300:	learn: 5.8283523	test: 5.8557952	test1: 4.2773437	best: 4.2772811 (293)	total: 42.9s	remaining: 7m 4s
400:	learn: 5.7773143	test: 5.8027321	test1: 4.2657451	best: 4.2657451 (400)	total: 57.4s	remaining: 6m 52s
500:	learn: 5.5276316	test: 5.5658849	test1: 4.2257276	best: 4.2257276 (500)	total: 1m 18s	remaining: 7m 14s
600:	learn: 5.0502787	test: 5.2726280	test1: 4.1892586	best: 4.1887648 (593)	total: 1m 59s	remaining: 8m 51s
Stopped by overfitting detector  (35 iterations wait)

bestTest = 4.187250662
bestIteration = 604

Shrink model to first 605 iterations.


[I 2021-12-22 00:59:48,883] Trial 3 finished with value: 4.187250662403432 and parameters: {'learning_rate': 0.024964236009425527, 'bagging_temperature': 0.011889379831773014, 'n_estimators': 3279, 'max_depth': 11, 'random_strength': 62, 'colsample_bylevel': 0.9662488471087745, 'l2_leaf_reg': 2.0457790770113467e-05, 'min_child_samples': 39, 'max_bin': 331, 'od_type': 'IncToDec'}. Best is trial 3 with value: 4.187250662403432.


0:	learn: 5.7714438	test: 5.7714438	test1: 5.6737201	best: 5.6737201 (0)	total: 8.51ms	remaining: 12.3s
100:	learn: 5.7043761	test: 5.6935763	test1: 5.6137594	best: 5.6137594 (100)	total: 4.77s	remaining: 1m 3s
200:	learn: 5.6711118	test: 5.6532986	test1: 5.5851707	best: 5.5851707 (200)	total: 9.57s	remaining: 59.3s
300:	learn: 5.6512953	test: 5.6227263	test1: 5.5706211	best: 5.5706030 (299)	total: 14.4s	remaining: 54.6s
400:	learn: 5.5897511	test: 5.5284997	test1: 5.5503612	best: 5.5503612 (400)	total: 19.5s	remaining: 50.8s


[I 2021-12-22 01:00:15,466] Trial 4 finished with value: 5.531159854064496 and parameters: {'learning_rate': 0.02924488608177781, 'bagging_temperature': 4.814503186400563, 'n_estimators': 1446, 'max_depth': 5, 'random_strength': 31, 'colsample_bylevel': 0.6182264625655736, 'l2_leaf_reg': 1.7110201144832212e-05, 'min_child_samples': 47, 'max_bin': 497, 'od_type': 'Iter'}. Best is trial 3 with value: 4.187250662403432.


Stopped by overfitting detector  (35 iterations wait)

bestTest = 5.531159854
bestIteration = 461

Shrink model to first 462 iterations.
0:	learn: 5.9392035	test: 5.9392035	test1: 4.9328352	best: 4.9328352 (0)	total: 6.13ms	remaining: 10s
100:	learn: 5.8369569	test: 5.8387774	test1: 4.8737808	best: 4.8737808 (100)	total: 8.84s	remaining: 2m 14s
200:	learn: 5.7582196	test: 5.7623913	test1: 4.8378364	best: 4.8378364 (200)	total: 20.3s	remaining: 2m 25s
300:	learn: 5.7070217	test: 5.6956851	test1: 4.8252495	best: 4.8249740 (289)	total: 29.8s	remaining: 2m 12s
400:	learn: 5.6461796	test: 5.6437510	test1: 4.8191872	best: 4.8191754 (399)	total: 39.8s	remaining: 2m 2s
500:	learn: 5.6187107	test: 5.6076935	test1: 4.8146560	best: 4.8146560 (500)	total: 48.2s	remaining: 1m 49s
600:	learn: 5.5762084	test: 5.5722570	test1: 4.8087753	best: 4.8087753 (600)	total: 59.3s	remaining: 1m 42s
700:	learn: 5.5220695	test: 5.5208693	test1: 4.8036276	best: 4.8035233 (697)	total: 1m 10s	remaining: 1m 34s
800:	

[I 2021-12-22 01:01:39,113] Trial 5 finished with value: 4.801909345244634 and parameters: {'learning_rate': 0.012964343050586333, 'bagging_temperature': 4.096691887503098, 'n_estimators': 1640, 'max_depth': 10, 'random_strength': 24, 'colsample_bylevel': 0.49538175018731184, 'l2_leaf_reg': 3.320150483517511e-06, 'min_child_samples': 68, 'max_bin': 241, 'od_type': 'Iter'}. Best is trial 3 with value: 4.187250662403432.


0:	learn: 5.5447998	test: 5.5447998	test1: 6.5154911	best: 6.5154911 (0)	total: 9.43ms	remaining: 40.3s
100:	learn: 5.4805808	test: 5.4835412	test1: 6.4608380	best: 6.4608380 (100)	total: 4.46s	remaining: 3m 4s
200:	learn: 5.4548110	test: 5.4585840	test1: 6.4402210	best: 6.4402210 (200)	total: 8.39s	remaining: 2m 49s
300:	learn: 5.4285670	test: 5.4277022	test1: 6.4169755	best: 6.4169755 (300)	total: 13.1s	remaining: 2m 53s
400:	learn: 5.3604336	test: 5.3553872	test1: 6.3238276	best: 6.3238276 (400)	total: 19.4s	remaining: 3m 7s
500:	learn: 5.2449893	test: 5.2519678	test1: 6.0847760	best: 6.0847760 (500)	total: 27.6s	remaining: 3m 27s
600:	learn: 5.1936107	test: 5.1890413	test1: 5.9647572	best: 5.9636713 (572)	total: 36s	remaining: 3m 39s
700:	learn: 5.1667666	test: 5.1709187	test1: 5.9351322	best: 5.9350260 (699)	total: 44.4s	remaining: 3m 45s
800:	learn: 5.1365858	test: 5.1545530	test1: 5.9270048	best: 5.9262721 (781)	total: 52.8s	remaining: 3m 48s
Stopped by overfitting detector  (35

[I 2021-12-22 01:02:37,335] Trial 6 finished with value: 5.890308081042156 and parameters: {'learning_rate': 0.03748432040341084, 'bagging_temperature': 0.024457108102318853, 'n_estimators': 4271, 'max_depth': 5, 'random_strength': 98, 'colsample_bylevel': 0.681190720988621, 'l2_leaf_reg': 2.930306503482821e-05, 'min_child_samples': 63, 'max_bin': 422, 'od_type': 'Iter'}. Best is trial 3 with value: 4.187250662403432.


0:	learn: 5.6904184	test: 5.6902175	test1: 5.9879130	best: 5.9879130 (0)	total: 131ms	remaining: 2m 15s
100:	learn: 5.6359907	test: 5.6334149	test1: 5.9376312	best: 5.9376312 (100)	total: 6.53s	remaining: 1m
200:	learn: 5.6016713	test: 5.5981634	test1: 5.9085021	best: 5.9085021 (200)	total: 13.5s	remaining: 55.8s
300:	learn: 5.5729659	test: 5.5713292	test1: 5.8845704	best: 5.8845655 (297)	total: 21.1s	remaining: 51.3s
400:	learn: 5.5601280	test: 5.5589116	test1: 5.8764543	best: 5.8764541 (396)	total: 26.5s	remaining: 41.8s
500:	learn: 5.5452093	test: 5.5451141	test1: 5.8639579	best: 5.8639579 (500)	total: 33.4s	remaining: 35.6s
600:	learn: 5.5319269	test: 5.5314493	test1: 5.8544918	best: 5.8544918 (599)	total: 39.4s	remaining: 28.4s
700:	learn: 5.5211388	test: 5.5222130	test1: 5.8491791	best: 5.8491791 (700)	total: 45.7s	remaining: 21.7s
800:	learn: 5.5097509	test: 5.5110356	test1: 5.8402112	best: 5.8402046 (797)	total: 52.1s	remaining: 15.1s
900:	learn: 5.4845462	test: 5.4787827	test1

[I 2021-12-22 01:03:47,561] Trial 7 finished with value: 5.579773485029631 and parameters: {'learning_rate': 0.012134273819353582, 'bagging_temperature': 0.15295398277813735, 'n_estimators': 1034, 'max_depth': 8, 'random_strength': 41, 'colsample_bylevel': 0.4384884978092706, 'l2_leaf_reg': 2.0777238859906895e-05, 'min_child_samples': 59, 'max_bin': 279, 'od_type': 'IncToDec'}. Best is trial 3 with value: 4.187250662403432.


0:	learn: 5.8278253	test: 5.8276356	test1: 5.4288706	best: 5.4288706 (0)	total: 127ms	remaining: 4m 5s
100:	learn: 5.5389794	test: 5.4864448	test1: 5.1610599	best: 5.1610599 (100)	total: 21.1s	remaining: 6m 22s
200:	learn: 5.3630824	test: 5.3573215	test1: 5.0547185	best: 5.0547185 (199)	total: 45.4s	remaining: 6m 31s
300:	learn: 5.2111779	test: 5.2395912	test1: 4.9802014	best: 4.9802014 (300)	total: 1m 7s	remaining: 6m 7s
400:	learn: 5.1031280	test: 5.1986359	test1: 4.9515298	best: 4.9515298 (400)	total: 1m 30s	remaining: 5m 45s
500:	learn: 4.8855913	test: 5.1179927	test1: 4.8937431	best: 4.8933776 (495)	total: 2m 8s	remaining: 6m 7s
600:	learn: 4.5500880	test: 5.0642946	test1: 4.8629201	best: 4.8629201 (600)	total: 3m 8s	remaining: 6m 58s
700:	learn: 4.3003285	test: 5.0253706	test1: 4.8531846	best: 4.8531846 (700)	total: 4m 10s	remaining: 7m 19s
Stopped by overfitting detector  (35 iterations wait)

bestTest = 4.851281264
bestIteration = 730

Shrink model to first 731 iterations.


[I 2021-12-22 01:08:39,026] Trial 8 finished with value: 4.851281264465326 and parameters: {'learning_rate': 0.025267910183518975, 'bagging_temperature': 52.1416524244723, 'n_estimators': 1933, 'max_depth': 12, 'random_strength': 13, 'colsample_bylevel': 0.8297963224711393, 'l2_leaf_reg': 8.689288727486561e-06, 'min_child_samples': 22, 'max_bin': 376, 'od_type': 'Iter'}. Best is trial 3 with value: 4.187250662403432.


0:	learn: 5.8385935	test: 5.8385935	test1: 5.3919268	best: 5.3919268 (0)	total: 8.11ms	remaining: 13.9s
100:	learn: 5.7933884	test: 5.7973142	test1: 5.3598717	best: 5.3598680 (98)	total: 13.8s	remaining: 3m 40s
200:	learn: 5.7536319	test: 5.7589215	test1: 5.3306094	best: 5.3306094 (200)	total: 31.3s	remaining: 3m 55s
300:	learn: 5.7280705	test: 5.7357856	test1: 5.3126493	best: 5.3126493 (300)	total: 46.9s	remaining: 3m 40s
400:	learn: 5.7020999	test: 5.7206935	test1: 5.3012027	best: 5.3012027 (400)	total: 59.1s	remaining: 3m 13s
500:	learn: 5.6792583	test: 5.7000905	test1: 5.2871595	best: 5.2871595 (500)	total: 1m 16s	remaining: 3m 6s
600:	learn: 5.6404115	test: 5.6705756	test1: 5.2670306	best: 5.2670306 (600)	total: 1m 34s	remaining: 2m 54s
700:	learn: 5.6135425	test: 5.6469243	test1: 5.2498353	best: 5.2498353 (700)	total: 1m 51s	remaining: 2m 41s
800:	learn: 5.5830766	test: 5.6222166	test1: 5.2335607	best: 5.2335607 (800)	total: 2m 11s	remaining: 2m 30s
900:	learn: 5.5650432	test: 5.

[I 2021-12-22 01:17:08,084] Trial 9 finished with value: 4.972580068839638 and parameters: {'learning_rate': 0.010075857041767923, 'bagging_temperature': 5.143587677210171, 'n_estimators': 1715, 'max_depth': 13, 'random_strength': 97, 'colsample_bylevel': 0.5492518861119748, 'l2_leaf_reg': 1.7288958459190928e-05, 'min_child_samples': 61, 'max_bin': 372, 'od_type': 'Iter'}. Best is trial 3 with value: 4.187250662403432.


4.187250662403432
{'learning_rate': 0.024964236009425527, 'bagging_temperature': 0.011889379831773014, 'n_estimators': 3279, 'max_depth': 11, 'random_strength': 62, 'colsample_bylevel': 0.9662488471087745, 'l2_leaf_reg': 2.0457790770113467e-05, 'min_child_samples': 39, 'max_bin': 331, 'od_type': 'IncToDec'}


In [21]:
my_param = {'learning_rate': 0.024964236009425527, 
            'bagging_temperature': 0.011889379831773014, 
            'n_estimators': 3279, 
            'max_depth': 11, 
            'random_strength': 62, 
            'colsample_bylevel': 0.9662488471087745, 
            'l2_leaf_reg': 2.0457790770113467e-05, 
            'min_child_samples': 39, 
            'max_bin': 331, 
            'od_type': 'IncToDec'
}
cat_param={'learning_rate': 0.018272261776066247, 
           'bagging_temperature': 63.512210106407046, 
           'n_estimators': 3794, 
           'max_depth': 11, 
           'random_strength': 15, 
           'colsample_bylevel': 0.49359671220172163, 
           'l2_leaf_reg': 1.7519275289243016e-06, 
           'min_child_samples': 88, 
           'max_bin': 380, 
           'od_type': 'IncToDec'
}

In [34]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=0)
folds = []
for train_idx, val_idx in skf.split(train.drop('INVC_CONT', axis=1), train['INVC_CONT']):
    folds.append((train_idx, val_idx))

len(folds)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning:

The least populated class in y has only 1 members, which is less than n_splits=10.



10

In [38]:
folds[:5]

[(array([    1,     3,     4, ..., 31997, 31998, 31999]),
  array([    0,     2,    16, ..., 31937, 31938, 31979])),
 (array([    0,     1,     2, ..., 31994, 31995, 31999]),
  array([    5,     6,    11, ..., 31996, 31997, 31998])),
 (array([    0,     1,     2, ..., 31997, 31998, 31999]),
  array([   10,    35,    39, ..., 31956, 31967, 31975])),
 (array([    0,     1,     2, ..., 31997, 31998, 31999]),
  array([    3,     7,    23, ..., 31981, 31984, 31985])),
 (array([    0,     1,     2, ..., 31997, 31998, 31999]),
  array([    9,    12,    14, ..., 31934, 31943, 31946]))]

In [40]:
import random

random.seed(0)
cat_feat = range(test.shape[1])
cat_models = {}
for fold in range(10):
    print(f'==========={fold + 1}===========')
    train_idx, val_idx = folds[fold]

    X_train, y_train = X.iloc[train_idx], y[train_idx]
    X_val,   y_val   = X.iloc[val_idx], y[val_idx]

    model = CatBoostRegressor(**cat_param)
    model.fit(
        X_train, y_train,
        eval_set=[(X_train, y_train), (X_val, y_val)], 
        early_stopping_rounds=35,
        cat_features=cat_feat,
        verbose=100
    )
    cat_models[fold] = model
    print(f'================================')

===========1===========
0:	learn: 5.6225880	test: 5.6233719	test1: 6.7820769	best: 6.7820769 (0)	total: 283ms	remaining: 17m 53s
100:	learn: 5.4822723	test: 5.5002465	test1: 6.6500220	best: 6.6500220 (100)	total: 15.8s	remaining: 9m 38s
200:	learn: 5.4096143	test: 5.4294630	test1: 6.5533355	best: 6.5533355 (198)	total: 31.1s	remaining: 9m 15s
300:	learn: 5.3477825	test: 5.3665657	test1: 6.4471157	best: 6.4471129 (299)	total: 45.7s	remaining: 8m 49s
400:	learn: 5.2849684	test: 5.3225355	test1: 6.3829976	best: 6.3829976 (400)	total: 59s	remaining: 8m 19s
500:	learn: 5.2358208	test: 5.2980434	test1: 6.3532722	best: 6.3532722 (500)	total: 1m 11s	remaining: 7m 49s
600:	learn: 5.1665163	test: 5.2609930	test1: 6.2815600	best: 6.2815600 (600)	total: 1m 26s	remaining: 7m 38s
700:	learn: 4.9804469	test: 5.1424877	test1: 6.0061928	best: 6.0061928 (700)	total: 1m 49s	remaining: 8m 1s
800:	learn: 4.7403428	test: 5.0515295	test1: 5.8296847	best: 5.8296847 (800)	total: 2m 22s	remaining: 8m 53s
900:	l

In [41]:
sub

index  INVC_CONT
0     32000          0
1     32001          0
2     32002          0
3     32003          0
4     32004          0
...     ...        ...
4635  36635          0
4636  36636          0
4637  36637          0
4638  36638          0
4639  36639          0

[4640 rows x 2 columns]

In [63]:
sub['INVC_CONT'] = np.mean([cat_models[i].predict(test) for i in range(10)], axis=0)

In [64]:
sub

index  INVC_CONT
0     32000   4.966044
1     32001   5.122518
2     32002   5.602061
3     32003   5.636876
4     32004   5.692881
...     ...        ...
4635  36635   5.003155
4636  36636   5.397189
4637  36637   4.452174
4638  36638   4.760048
4639  36639   4.701106

[4640 rows x 2 columns]

In [65]:
 sub[sub['INVC_CONT'] >= 30]

index  INVC_CONT
1306  33306  43.413699
3089  35089  55.667945

In [66]:
sub.loc[sub['INVC_CONT'] > 30, 'INVC_CONT'] = sub.loc[sub['INVC_CONT'] > 30, 'INVC_CONT'] * 4.8

In [68]:
sub

index  INVC_CONT
0     32000   4.966044
1     32001   5.122518
2     32002   5.602061
3     32003   5.636876
4     32004   5.692881
...     ...        ...
4635  36635   5.003155
4636  36636   5.397189
4637  36637   4.452174
4638  36638   4.760048
4639  36639   4.701106

[4640 rows x 2 columns]